Repository ms-club-sliit/minihackathon-2022, pull requests merged in 2022-06, with the labels that each got.

#22 Implemented UI for rules section
  src/App.js
  src/views/index.js
  src/views/rules/index.jsx
Labels: view

#23 Header component implemented
  package-lock.json
  package.json
  src/components/Header/Header.jsx
  src/index.js
Labels: ui component

#24 Implement Gallery View
  package.json
  src/App.js
  src/asserts/img1.webp
  src/asserts/img2.webp
  src/asserts/img3.webp
  src/asserts/img4.webp
  src/asserts/img5.webp
  src/asserts/img6.webp
  src/asserts/img7.webp
  src/index.css
  src/views/Gallery/Gallery.jsx
  src/views/index.js
  yarn.lock
Labels: enhancement, ui component, view

#32 fixed lint errors and implemented the scroll
  package.json
  src/components/Navbar/index.jsx
  src/views/Gallery/index.jsx
  src/views/Timeline/index.jsx
  src/views/rules/index.jsx
  yarn.lock
Labels: bug

#27 Prettier Config Done
  package.json
  yarn.lock
Labels: configuration

#35 Logo & Countdown Timer Implemented
  package.json
  public/index.html
  src/App.js
  src/asserts/minihackthon2019/logo/mini_hackathon_logo.webp
  src/util/CountdownTimerUtils.js
  src/views/Countdown/CountdownTimer.js
  src/views/Countdown/index.jsx
  src/views/index.js
  tailwind.config.js
  yarn.lock
Labels: view, design

#36 Feature/29 register api
  public/assets/mini_hackathon_logo.png
  src/App.css
  src/App.js
  src/Firebase.js
  src/api/register/index.js
  src/api/team/index.js
  src/asserts/minihackthon2019/logo/mini_hackathon_logo.webp
  src/asserts/mlsa/mlsalogo.webp
  src/asserts/msclub/mslogo.webp
  src/assets/gallery/img1.webp
  src/assets/gallery/img2.webp
  src/assets/gallery/img3.webp
  src/assets/gallery/img4.webp
  src/assets/gallery/img5.webp
  src/assets/gallery/img6.webp
  src/assets/gallery/img7.webp
  src/assets/logo/mini_hackathon_logo.png
  src/assets/logo/mlsa_logo.png
  src/assets/logo/ms_club_logo.png
  src/assets/logo/ms_club_logo_bg.png
  src/assets/logo/ms_club_logo_light.png
  src/assets/sponsors/company_logo.webp
  src/components/Footer/index.jsx
  src/components/Navbar/index.jsx
  src/components/Timeline/index.jsx
  src/components/TimelineCard/index.jsx
  src/components/index.js
  src/utils/countdownTimerUtils.js
  src/views/Countdown/index.jsx
  src/views/Eligibility/index.jsx
  src/views/Gallery/index.jsx
  src/views/Header/CountdownTimer.jsx
  src/views/Header/index.jsx
  src/views/Sponsors/index.jsx
  src/views/Timeline/index.jsx
  src/views/index.js
  src/views/register/MemberForm.jsx
  src/views/register/index.jsx
  src/views/rules/index.jsx
Labels: enhancement, high priority, api

#51 Local configuration for the project (#50)
  package.json
  yarn.lock
Labels: configuration, high priority

#54 8 online ticket
  package.json
  public/assets/mini_hackathon_logo.webp
  src/assets/logo/mini_hackathon_logo.png
  src/components/Footer/index.jsx
  src/components/Navbar/index.jsx
  src/components/Ticket/index.jsx
  src/components/index.js
  src/configs/index.js
  src/data/Sessions.json
  src/utils/emailSend.js
  src/views/Sponsors/index.jsx
  src/views/Timeline/index.jsx
  yarn.lock
Labels: enhancement, ui component, high priority

#55 Development to Staging
  package.json
  public/assets/mini_hackathon_logo.webp
  src/assets/logo/mini_hackathon_logo.png
  src/components/Footer/index.jsx
  src/components/Navbar/index.jsx
  src/components/Ticket/index.jsx
  src/components/index.js
  src/configs/index.js
  src/data/Sessions.json
  src/utils/emailSend.js
  src/views/Sponsors/index.jsx
  src/views/Timeline/index.jsx
  yarn.lock
Labels: high priority

#56 Staging to Production
  package.json
  public/assets/mini_hackathon_logo.webp
  src/assets/logo/mini_hackathon_logo.png
  src/components/Footer/index.jsx
  src/components/Navbar/index.jsx
  src/components/Ticket/index.jsx
  src/components/index.js
  src/configs/index.js
  src/data/Sessions.json
  src/utils/emailSend.js
  src/views/Sponsors/index.jsx
  src/views/Timeline/index.jsx
  yarn.lock
Labels: high priority

#25 Implement card for team overview
  src/components/TeamCard/index.jsx
  src/components/index.js
Labels: ui component

#57 feat(Team view) : ms-club-sliit#14 Team view
  .idea/workspace.xml
  src/App.js
  src/components/TeamCard/index.jsx
Labels: bug, ui component, design

#59 Development
  .gitignore
  CHANGELOG.md
  firebase.json
  public/assets/pastwinners/AlphaSquard.webp
  public/assets/pastwinners/BringTheSolution.webp
  public/assets/pastwinners/TeamCareCycle.webp
  src/App.css
  src/App.js
  src/components/PastWinner/index.jsx
  src/components/TeamCard/index.jsx
  src/components/index.js
  src/data/PastWinners.json
  src/data/TeamCard.json
  src/views/Gallery/index.jsx
  src/views/PastWinners/index.jsx
  src/views/TeamView/index.jsx
  src/views/index.js
Labels: high priority

#64 Feature/page rotues
  .gitignore
  package.json
  src/App.css
  src/App.js
  src/PageRoutes.js
  src/api/register/index.js
  src/components/TimelineCard/index.jsx
  src/views/Home/index.js
  src/views/Register/index.jsx
  src/views/index.js
  yarn.lock
Labels: view, high priority

#65 Development
  .gitignore
  package.json
  src/App.css
  src/App.js
  src/PageRoutes.js
  src/api/register/index.js
  src/components/TimelineCard/index.jsx
  src/views/Home/index.js
  src/views/Register/index.jsx
  src/views/index.js
  yarn.lock
Labels: enhancement, medium priority
