Repository ms-club-sliit/minihackathon-2022, pull requests merged in 2022-07, with the labels that each got.

#69 Emali fixes, styles and much more.
  src/api/register/index.js
  src/components/Ticket/index.jsx
  src/views/AwarenessSession/EmailTemplate.jsx
  src/views/AwarenessSession/index.jsx
  src/views/Header/index.jsx
  src/views/Register/MemberForm2.jsx
  src/views/Register/NameForm.jsx
  src/views/Register/index.jsx
Labels: high priority

#98 Merge branch 'staging' of https://github.com/ms-club-sliit/minihackat…
  public/assets/fcsc_logo.png
  src/PageRoutes.js
  src/components/TeamTicket/index.jsx
  src/components/Ticket/index.jsx
  src/components/TicketPopup/index.jsx
  src/components/TimelineCard/index.jsx
  src/views/AwarenessSession/index.jsx
  yarn.lock
Labels: ui component, view, high priority

#105 Bug - TeamView is not mobile responsive #62
  src/components/Navbar/index.jsx
  src/components/TeamCard/index.jsx
  src/views/Header/index.jsx
  src/views/TeamView/index.jsx
  yarn.lock
Labels: bug, high priority
